### ISSUE TITLE
empty typos

### ISSUE THREAD

**Issue by leorosa** [fischerling/vis-spellcheck#1]
I got the warning below, from which the editor must be manually killed:
```
(..)/spellcheck.lua:50: attempt to index a nil value (local 'typos')
```
It appears that texts without errors trigger it.

**Comment by fischerling** [comment]
Thank you very much for pointing this out.
I you have other problems or can think of a more efficient way to do spell checking
in vis let me know.

**Comment by leorosa** [comment]
Thanks for the (quick) fix. 

I have only a suggestion. Personally, I prefer to enable/disable spell check using the same key (mapped in `visrc`). To do this, a function like the one below is needed in `spellcheck.lua`:
```
function spellcheck_toggle(keys)
	if not spellcheck.enabled[vis.win] then
		spellcheck.enabled[vis.win] = true
	else
		spellcheck.enabled[vis.win] = nil
		vis.win:draw()
	end
	return 0
end
```
This may be useful for other users.

**Comment by fischerling** [comment]
I would happily accept such a pull request.
Otherwise I could commit the code snipped from your comment maybe with some default mapping.

**Comment by leorosa** [comment]
Feel free to commit the code snipped. I map it to <F7> in my `visrc.lua`, similar to the keys used by libreoffice for spell checks.
