### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by adigitoleo** [fischerling/vis-spellcheck#8]
Hey, I'm just trying out vis, I wonder if anyone can help. When I add this plugin I get an error at startup:

```
/usr/share/vis/plugins/spellcheck.lua:35: attempt to index a nil value (field 'lexers')
```

My vis version is `vis v0.7 +curses +lua +tre +acl`. Am I missing some dependencies? Compiler flags? I'm not loading any other plugins.

**Comment by adigitoleo** [comment]
Oh dear, that's embarrassing: I didn't have `require('vis')`. https://github.com/martanne/vis/wiki/Plugins

**Comment by fischerling** [comment]
I am glad that it works now :)
If you encounter anything odd please feel to reach out.
